<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/x html1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
  <title>RAL |  | Weather Systems and Assessment Program</title>
  	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="Description" content="The Research Applications Laboratory (RAL)" />
	<meta name="distribution" content="global" />
	<meta name="rating" content="general" />

	<meta name="robots" content="index,follow" />
	<meta name="revisit-after" content="4 Days" />
	<meta name="copyright" content="Copyright (c) 2007 by UCAR" />
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

	<link rel="shortcut icon" href="http://www.rap.ucar.edu/favicon.ico" type="image/x-icon" />
    
    
    
    
    <!-- NCAR CSS -->
	<link rel="stylesheet" href="http://www.rap.ucar.edu/styles/universal_orgnav.css" type="text/css" media="screen">
	<link rel="stylesheet" href="http://www.rap.ucar.edu/styles/site_mainnav.css" type="text/css" media="screen">

	<link rel="stylesheet" href="http://www.rap.ucar.edu/styles/site_subnavigation.css" type="text/css" media="screen">
	<link rel="stylesheet" href="http://www.rap.ucar.edu/styles/ncar_subpage_layout.css" type="text/css" media="screen">
	<link rel="stylesheet" href="http://www.rap.ucar.edu/styles/ncar_class_styles2.css" type="text/css" media="screen">
    <link rel="stylesheet" href="http://www.rap.ucar.edu/styles/ncar_printstyles.css" type="text/css"  media="print">

    <!-- RAL CSS -->

    <style type="text/css">	    @import url("http://www.rap.ucar.edu/styles/ral_subpage_layout.css");</style>

	
	<!-- Equal Height Columns -->

	<script type="text/javascript" src="http://www.rap.ucar.edu/scripts/column_height_equal.js"></script>
	
		<!-- SPRY Tabbed Panels -->
	
	<link href="http://www.rap.ucar.edu/scripts/widgets/tabbedpanels/SpryTabbedPanels_ncarResearch.css" rel="stylesheet" type="text/css" />
	<script language="JavaScript" type="text/javascript" src="http://www.rap.ucar.edu/scripts/widgets/tabbedpanels/SpryTabbedPanels.js"></script>

	<!--  New Pop up Window -->

	<script src="http://www.rap.ucar.edu/scripts/popups.js" type="text/javascript"></script>

	
	<!-- Flyout Leftnav -->

	<script type="text/javascript" src="http://www.rap.ucar.edu/scripts/vertical_menu2.js"></script>
	</head>
<body>
	<div id="top_colorbar"><!-- begin top_colorbar -->
	</div><!-- end top_colorbar -->

    <div id="nav_org_wrap"><!-- begin nav_org_wrap -->
        		<div id="nav_org"><!-- begin nav_org -->

			

<ul class="menubar">


<li><a class="trigger" href="http://www.ucar.edu">UCAR</a>
<ul>
<li><a href="http://www.ucar.edu" title="University Corporation for Atmospheric Research">University Corporation for Atmospheric Research</a></li>
<li><a href="http://www.ucar.edu/pres/" title="UCAR President's Office">President's Office</a></li>

<li><a href="http://www.ucar.edu/news/" title="NCAR &amp; UCAR News, Media Relations, Publications">Communications - News Center</a></li>
<li><a href="http://www.ucar.edu/tools/education.jsp"  title="EO, Internships, SOARS, Tours & Exhibits, UOP Education & Training">Education &amp; Outreach</a></li>
<li><a href="http://www.fin.ucar.edu/"  title="F&A: B&F, Contracts, Counsel, HR, UCAR IT, Physical Plant, Safety, Treas">Finance &amp; Administration</a></li>
<li><a href="http://www.ucar.edu/governance/index.jsp"  title="Gov: Board of Trustees, Members, Affiliates, University Relations">Governance/Members/Affiliates</a></li>
<li><a href="http://www.ucar.edu/oga/"  title="OGA: Federal Budgets, Advocacy, Legislative Update, Hill Events">Office of Government Affairs</a></li>
</ul>
</li>

<li><a class="trigger" href="http://www.ncar.ucar.edu">NCAR</a>
<ul>
<li><a href="http://www.ncar.ucar.edu" title="National Center for Atmospheric Research">National Center for Atmospheric Research</a></li>
<li><a href="http://www.ncar.ucar.edu/ncardir/" title="NCAR Director's Office">Director's Office</a></li>
<li><a href="http://www.ncar.ucar.edu/planning/" title="NCAR Budget &amp; Planning Office">Budget &amp; Planning</a></li>
<li><a href="http://www.ncar.ucar.edu/resrel/" title="NCAR Research Relations Office">Research Relations</a></li>
<li><a href="http://www.ncar.ucar.edu/ncarlibrary/"  title="NCAR Libraries: Mesa Lab, Foothills Lab, Center Green">NCAR Library</a></li>
<li><a href="http://www.cisl.ucar.edu" title="CISL Divisions: IMAGe, OSD, TDD">Computational &amp; Information Systems Laboratory</a></li>

<li><a href="http://www.eol.ucar.edu"  title="EOL Divisions: CDS, DFS, FPS, ISF, RAF, RSF, TDF">Earth Observing Laboratory</a></li>
<li><a href="http://www.essl.ucar.edu"  title="ESSL Divisions: ACD, CGD, HAO, MMM, TIIMES">Earth &amp; Sun Systems Laboratory</a></li>
<li><a href="http://www.ral.ucar.edu"  title="RAL Divisions: AAP, HAP, JNT, NSAP, WSAP">Research Applications Laboratory</a></li>
<li><a href="http://www.sere.ucar.edu"  title="SERE Divisions: ASP, CCB, ISSE">Societal-Environmental &amp; Research and Education Laboratory</a></li>
</ul>
</li>

<li><a class="trigger" href="http://www.uop.ucar.edu">UOP</a>

<ul>
<li><a href="http://www.uop.ucar.edu" title="UCAR Office of Programs">UCAR Office of Programs</a></li>
<li><a href="http://www.uop.ucar.edu/directors_office.html" title="UOP Director's Office">Director's Office</a></li>
<li><a href="http://www.comet.ucar.edu/" title="Cooperative Program for Operational Meteorology, Education & Training">COMET</a></li>
<li><a href="http://www.cosmic.ucar.edu/" title="Constellation Observing System for Meteorology, Ionosphere & Climate">COSMIC</a></li>
<li><a href="http://dlsciences.org " title="Digital Learning Sciences">DLS</a></li>
<li><a href="http://www.globe.gov/fsl/html/templ.cgi?about" title="Global Learning & Observations to Benefit the Environment">GLOBE</a></li>
<li><a href="http://www.joss.ucar.edu/" title="Joint Office for Science Support: meetings, travel, logistics">JOSS</a></li>
<li><a href="http://www.joss.ucar.edu/" title="COMET's Meteorology Education & Training: online courses, webcasts">MetEd</a></li>

<li><a href="http://nsdl.org/" title="National Science Digital Library Central Office">NSDL</a></li>
<li><a href="http://www.unidata.ucar.edu/" title="Unidata Program Center: weather and climate data, tools, community">Unidata</a></li>
<li><a href="http://www.vsp.ucar.edu/" title="Visiting Scientist Programs: internships and fellowships at national labs">VSP</a></li>
</ul>
</li>
</ul>


		</div><!-- end nav_org -->

		<div id="search"><!-- begin search -->

			
<ul class="menubar">

<li><a class="trigger" href="http://www.people.ucar.edu/">Find People</a>

	<ul class="dropleftorg">
	<li><a href="http://www.people.ucar.edu/" title="UCAR-wide People Search">UCAR-wide People Search</a></li>
	</ul>

</li>

<li><a class="trigger" href="http://www.ncar.ucar.edu/organization/about/">Contact/Visit</a>

	<ul class="dropleftorg">
	<li><a href="http://www.ncar.ucar.edu/organization/about/" title="NCAR Maps and Directions">Contact or Visit NCAR</a></li>
	<li><a href="http://www.ucar.edu/org/bouldermap.shtml" title="NCAR Maps and Directions">UCAR's Maps and Directions Page</a></li>
	</ul>

</li>

</ul>

		</div><!-- end search --></div>

	</div><!-- end nav_org_wrap -->
	<div id="nav_main_wrap"><!-- begin nav_main_wrap -->

		<div id="nav_main"><!-- begin nav_main -->
        <ul id="menubar_main">
		  <li><a href="http://www.rap.ucar.edu/">RAL home</a></li>
  <li><a href="http://www.rap.ucar.edu/research/">research</a></li>

  <li><a href="http://www.rap.ucar.edu/technology/">technology</a></li>
  <li><a href="http://www.rap.ucar.edu/directory/">people/org</a></li>
  <li><a href="http://www.rap.ucar.edu/general/pubs/">publications</a></li>
  <li><a href="http://www.rap.ucar.edu/general/events/">events</a></li>
  <li><a href="http://www.rap.ucar.edu/general/press/">pressroom</a></li>
  <li><a href="http://www.rap.ucar.edu/internal/">for staff</a></li>

         </ul>
		</div><!-- end nav_main -->

	</div><!-- end nav_main_wrap -->

<div id="wrap"><!-- begin wrap -->
	<div id="content"><!-- begin content -->
		<div id="subheader"><!-- begin subheader -->
            			<div id="ncarheader">
			<img src="http://www.rap.ucar.edu/images/header/ral_header.jpg"  alt="Website header">

			</div>
<div id="googlesearch">
				  <form name="google" method="get" action="http://www.google.com/u/ncar" >
                  <a href="http://www.ucar.edu/ucar/search_advanced.shtml">advanced</a>
                  <input type=hidden name=hq value="site:www.rap.ucar.edu">
                  <input type=submit name=sa  value="Search RAL">
                  <input type=text name=q size=20 maxlength=255>
                  </form> 

</div>	    </div><!-- end subheader -->

<style>

    #pagefeature {
	width: 938px; 
	float: left;
}
	
    #column_pagecontent {
	width: 938px; 
}

    #column_pagecontent #headingdiv h1 {
	width: 958px; 
}


    #wrap_pagecontent {
	width: 938px;
}
	
	.TabbedPanels {
	width: 938px; 
}        

	.TabbedPanelsContent {
	min-height: 10px;
}


#wrap_pagecontent a .large {
	border: 0px;
	display: block;
	height: 1px;
	left: -1px;
	top: -1px;
	width: 1px;
}


#wrap_pagecontent a.p1:hover {
	background-color: #8C97A3;
	color: #000000;
	text-decoration: none;
}

#wrap_pagecontent a.p1:hover .large {
	border: 1px solid #000000;
	display: block;
	height: 233px;
	left: 750px;
     position: absolute;
	top: 800px; 
	width: 300px; 
}

#wrap_pagecontent a.p2:hover .large {
	border: 1px solid #000000;
	display: block;
	height: 233px;
	left: 625px;
     position: absolute;
	top: 700px; 
	width: 300px; 
}

#wrap_pagecontent a.p3:hover .large {
	border: 1px solid #000000;
	display: block;
	height: 233px;
	left: 700px;
     position: absolute;
	top: 600px; 
	width: 300px; 
}


</style>





<!-- Begin main page content -->


