
<!--end main page content-->
<div id="footer"><!-- begin footer -->
<!--
  <hr />-->
         <p> &copy;2008, UCAR | <a href="http://www.ucar.edu/legal/privacy_policy.shtml">Privacy 
  Policy</a> | <a href="http://www.ucar.edu/legal/terms_of_use.shtml">Terms of 
  Use</a>
  <br />
  <em>Postal Address: P.O. Box 3000, Boulder, CO 80307-3000 &bull; Shipping Address: 1850 Table Mesa Drive, Boulder, CO 80305 &bull; <a href="http://www.rap.ucar.edu/general/about">Contact</a></em></p>

	</div><!-- end footer -->


		<br class="clearboth"/>


	</div><!-- end content -->

</div><!-- end wrap -->

</body>

</html>



