#!/bin/bash

docker build -t $IMAGE_NAME \
--build-arg METVIEWER_GIT_NAME=$SOURCE_BRANCH \
--build-arg METCALCPY_GIT_NAME=v1.1.0-beta6 \
--build-arg METDATAIO_GIT_NAME=v1.1.0-beta6 \
--build-arg METPLOTPY_GIT_NAME=v1.1.0-beta6 .

