#!/bin/bash

docker build -t $IMAGE_NAME \
--build-arg METVIEWER_GIT_NAME=$SOURCE_BRANCH \
--build-arg METCALCPY_GIT_NAME=v2.0.1 \
--build-arg METDATAIO_GIT_NAME=v2.0.1 \
--build-arg METPLOTPY_GIT_NAME=v2.0.1 .

