SELECT COUNT(*), 'stat_header' FROM stat_header UNION
SELECT COUNT(*), 'line_data_cnt' FROM line_data_cnt UNION
SELECT COUNT(*), 'line_data_ctc' FROM line_data_ctc UNION
SELECT COUNT(*), 'line_data_cts' FROM line_data_cts UNION
SELECT COUNT(*), 'line_data_fho' FROM line_data_fho UNION
SELECT COUNT(*), 'line_data_isc' FROM line_data_isc UNION
SELECT COUNT(*), 'line_data_mctc' FROM line_data_mctc UNION
SELECT COUNT(*), 'line_data_mctc_cnt' FROM line_data_mctc_cnt UNION
SELECT COUNT(*), 'line_data_mcts' FROM line_data_mcts UNION
SELECT COUNT(*), 'line_data_mpr' FROM line_data_mpr UNION
SELECT COUNT(*), 'line_data_nbrcnt' FROM line_data_nbrcnt UNION
SELECT COUNT(*), 'line_data_nbrctc' FROM line_data_nbrctc UNION
SELECT COUNT(*), 'line_data_nbrcts' FROM line_data_nbrcts UNION
SELECT COUNT(*), 'line_data_orank' FROM line_data_orank UNION
SELECT COUNT(*), 'line_data_orank_ens' FROM line_data_orank_ens UNION
SELECT COUNT(*), 'line_data_pct' FROM line_data_pct UNION
SELECT COUNT(*), 'line_data_pct_thresh' FROM line_data_pct_thresh UNION
SELECT COUNT(*), 'line_data_pjc' FROM line_data_pjc UNION
SELECT COUNT(*), 'line_data_pjc_thresh' FROM line_data_pjc_thresh UNION
SELECT COUNT(*), 'line_data_prc' FROM line_data_prc UNION
SELECT COUNT(*), 'line_data_prc_thresh' FROM line_data_prc_thresh UNION
SELECT COUNT(*), 'line_data_pstd' FROM line_data_pstd UNION
SELECT COUNT(*), 'line_data_pstd_thresh' FROM line_data_pstd_thresh UNION
SELECT COUNT(*), 'line_data_rhist' FROM line_data_rhist UNION
SELECT COUNT(*), 'line_data_rhist_rank' FROM line_data_rhist_rank UNION
SELECT COUNT(*), 'line_data_sal1l2' FROM line_data_sal1l2 UNION
SELECT COUNT(*), 'line_data_sl1l2' FROM line_data_sl1l2 UNION
SELECT COUNT(*), 'line_data_val1l2' FROM line_data_val1l2 UNION
SELECT COUNT(*), 'line_data_vl1l2' FROM line_data_vl1l2 UNION
SELECT COUNT(*), 'mode_header' FROM mode_header UNION
SELECT COUNT(*), 'mode_cts' FROM mode_cts UNION
SELECT COUNT(*), 'mode_obj_single' FROM mode_obj_single UNION
SELECT COUNT(*), 'mode_obj_pair' FROM mode_obj_pair 
