# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: JUnit CI

on:
  push:
    branches:
      - develop
      - develop-ref
      - feature_*
      - issue_*
      - main_*
      - bugfix_*
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Ant
        run: ant -Dpython.env.path=METviewer clean test-compile test
      - name: Run MV JUnit tests
        run: ant test
